name: Linter CI
on: [push, pull_request]
jobs:
 lint:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Ejecutar verificación de sintaxis
       run: echo "Simulación de linting o pruebas automatizadas"
